#! /usr/bin/env bash

set -x
set -eo pipefail

#DB_HOST="${POSTGRES_HOST:=localhost}"
DB_NAME="${POSTGRES_NAME:=newsletter}"
DB_PASSWORD="${POSTGRES_PASSWORD:=password}"
DB_PORT="${POSTGRES_PORT:=5432}"
DB_USER="${POSTGRES_USER:=postgres}"

num_connections=1000

docker run \
  -e POSTGRES_USER="$DB_USER" \
  -e POSTGRES_PASSWORD="$DB_PASSWORD" \
  -e POSTGRES_DB="$DB_NAME" \
  -p "$DB_PORT":5432 \
  postgres -N "$num_connections"
